name: pogo_tiled_example
description: Example app showing Tiled integration.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  pogo: ^0.2.1
  pogo_tiled:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/tiles/map.tmx
    - assets/images/map-level1.png
    - assets/images/map-level2.png
    - assets/images/coins.png
